import React, { useState } from 'react';
import Card from '../common/Card';
import Input from '../common/Input';
import Button from '../common/Button';
import styles from './OrderForm.module.css';

const InvoiceForm = ({ invoice, onSubmit, onCancel, nextInvoiceNumber }) => {
  const [formData, setFormData] = useState({
    order: invoice?.order || '',
    customer: invoice?.customer || '',
    customerAddress: invoice?.customerAddress || '',
    customerEmail: invoice?.customerEmail || '',
    date: invoice?.date || new Date().toISOString().split('T')[0],
    dueDate: invoice?.dueDate || new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: invoice?.status || 'unpaid'
  });

  const [lineItems, setLineItems] = useState(invoice?.items || [
    { id: Date.now(), description: '', quantity: 1, unitPrice: 0 }
  ]);
  
  const [paid, setPaid] = useState(invoice?.paid || 0);
  const [loading, setLoading] = useState(false);

  // Calculate totals
  const calculateSubtotal = () => {
    return lineItems.reduce((sum, item) => sum + (item.quantity * item.unitPrice), 0);
  };

  const calculateVAT = () => {
    return calculateSubtotal() * 0.15;
  };

  const calculateTotal = () => {
    return calculateSubtotal();
  };

  const calculateBalance = () => {
    return calculateTotal() - paid;
  };

  const formatCurrency = (amount) => {
    return `R ${amount.toLocaleString('en-ZA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  };

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleLineItemChange = (id, field, value) => {
    setLineItems(lineItems.map(item => 
      item.id === id ? { ...item, [field]: field === 'quantity' ? parseInt(value) || 0 : field === 'unitPrice' ? parseFloat(value) || 0 : value } : item
    ));
  };

  const addLineItem = () => {
    setLineItems([...lineItems, { id: Date.now() + Math.random(), description: '', quantity: 1, unitPrice: 0 }]);
  };

  const removeLineItem = (id) => {
    if (lineItems.length > 1) {
      setLineItems(lineItems.filter(item => item.id !== id));
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    
    const validLineItems = lineItems.filter(item => item.description.trim() !== '');
    
    const invoiceData = {
      ...formData,
      items: validLineItems.length > 0 ? validLineItems : lineItems,
      total: calculateTotal(),
      paid: parseFloat(paid) || 0
    };
    
    await onSubmit(invoiceData);
    setLoading(false);
  };

  const subtotal = calculateSubtotal();
  const vat = calculateVAT();
  const total = calculateTotal();
  const balance = calculateBalance();

  return (
    <Card className={styles.formCard}>
      <h3>{invoice ? 'Edit Invoice' : 'Create New Invoice'}</h3>
      
      {!invoice && nextInvoiceNumber && (
        <div className={styles.invoiceNumberPreview}>
          <span>Invoice Number: </span>
          <strong>{nextInvoiceNumber}</strong>
          <span className={styles.autoGenerated}>(Auto-generated)</span>
        </div>
      )}

      {invoice && (
        <div className={styles.invoiceNumberPreview}>
          <span>Invoice Number: </span>
          <strong>{invoice.invoiceNumber}</strong>
        </div>
      )}
      
      <form onSubmit={handleSubmit} className={styles.form}>
        <Input label="Order #" name="order" value={formData.order} onChange={handleChange} required />
        <Input label="Customer" name="customer" value={formData.customer} onChange={handleChange} required />
        <Input label="Customer Address" name="customerAddress" value={formData.customerAddress} onChange={handleChange} />
        <Input label="Customer Email" name="customerEmail" type="email" value={formData.customerEmail} onChange={handleChange} />
        <Input label="Date" name="date" type="date" value={formData.date} onChange={handleChange} required />
        <Input label="Due Date" name="dueDate" type="date" value={formData.dueDate} onChange={handleChange} required />
        
        {/* Line Items Section */}
        <div className={styles.lineItemsSection}>
          <div className={styles.lineItemsHeader}>
            <label className={styles.label}>Services / Line Items</label>
            <Button type="button" variant="default" size="small" onClick={addLineItem}>+ Add Item</Button>
          </div>
          
          {lineItems.map((item) => (
            <div key={item.id} className={styles.lineItemRow}>
              <div className={styles.lineItemDescription}>
                <Input
                  placeholder="Description (e.g., 1 Room House Cleaning)"
                  value={item.description}
                  onChange={(e) => handleLineItemChange(item.id, 'description', e.target.value)}
                />
              </div>
              <div className={styles.lineItemQuantity}>
                <Input
                  type="number"
                  min="1"
                  placeholder="Qty"
                  value={item.quantity}
                  onChange={(e) => handleLineItemChange(item.id, 'quantity', e.target.value)}
                />
              </div>
              <div className={styles.lineItemPrice}>
                <Input
                  type="number"
                  min="0"
                  step="0.01"
                  placeholder="Unit Price"
                  value={item.unitPrice}
                  onChange={(e) => handleLineItemChange(item.id, 'unitPrice', e.target.value)}
                />
              </div>
              <div className={styles.lineItemTotal}>
                <span>{formatCurrency(item.quantity * item.unitPrice)}</span>
              </div>
              {lineItems.length > 1 && (
                <button type="button" className={styles.removeBtn} onClick={() => removeLineItem(item.id)}>✕</button>
              )}
            </div>
          ))}
        </div>

        {/* Totals Section */}
        <div className={styles.totalsSection}>
          <div className={styles.totalRow}>
            <span>Subtotal:</span>
            <span>{formatCurrency(subtotal)}</span>
          </div>
          <div className={styles.totalRow}>
            <span>VAT (15%):</span>
            <span>{formatCurrency(vat)}</span>
          </div>
          <div className={`${styles.totalRow} ${styles.grandTotal}`}>
            <span>Total (VAT Incl):</span>
            <span>{formatCurrency(total)}</span>
          </div>
        </div>

        <Input 
          label="Amount Paid (R)" 
          name="paid" 
          type="number" 
          step="0.01" 
          min="0"
          value={paid} 
          onChange={(e) => setPaid(parseFloat(e.target.value) || 0)} 
        />
        
        <div className={styles.balanceDisplay}>
          <span>Balance Due:</span>
          <strong className={balance > 0 ? styles.balancePositive : styles.balanceZero}>
            {formatCurrency(balance)}
          </strong>
        </div>
        
        <div className={styles.formGroup}>
          <label className={styles.label}>Status</label>
          <select name="status" value={formData.status} onChange={handleChange} className={styles.select}>
            <option value="unpaid">Unpaid</option>
            <option value="partial">Partial</option>
            <option value="paid">Paid</option>
          </select>
        </div>

        <div className={styles.formActions}>
          <Button type="button" variant="default" onClick={onCancel}>Cancel</Button>
          <Button type="submit" variant="primary" loading={loading}>
            {invoice ? 'Update' : 'Create'} Invoice
          </Button>
        </div>
      </form>
    </Card>
  );
};

export default InvoiceForm;
